---
- name: eclipse-che-apb playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    postgresql_admin_password: admin123
    postgresql_version: 9.6
    database_name: keycloak
    _apb_plan_id: prod
  roles:
    - role: ansible.kubernetes-modules
      install_python_requirements: no
    - role: ansibleplaybookbundle.asb-modules
  tasks:
    - set_fact:
        token: "{{ lookup('env', 'OPENSHIFT_TOKEN' ) }}"
        ocp_host: "{{ lookup('env', 'OPENSHIFT_TARGET' ) }}"

    - name: "Login"
      command: "oc login --token={{ token }} --insecure-skip-tls-verify=true {{ ocp_host }}"
    - include_role:
        name: provision-eclipse-che-apb
      vars:
        cluster: openshift
