---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: codeready-workspaces
spec:
  clusterServiceClassExternalName: localregistry-codeready-workspaces-apb
  clusterServicePlanExternalName: prod
