---
- name: "Generate Identity Provider Secret and oAuth Client Name"
  set_fact:
    identity_provider_client_secret: "{{ lookup('password','/tmp/identity_provider_client_secret chars=ascii_letters,digits length=13') }}"
    oauth_client_name: "openshift-oauth-client-{{ lookup('password','/tmp/oauth_client_name chars=digits length=6') }}"

- name: "Generate keycloak auth token"
  uri:
    url: "{{ keycloak_uri | default(external_keycloak_uri) }}/auth/realms/master/protocol/openid-connect/token"
    method: POST
    body: "client_id=admin-cli&username={{ che_keycloak_admin_username }}&password={{ che_keycloak_admin_password }}&grant_type=password"
    validate_certs: no
  register: keycloak_auth_response
  until: keycloak_auth_response.status == 200
  retries: 100
  delay: 2

- name: "Register OpenShift V3 Identity Provider"
  uri:
    url: "{{ keycloak_uri | default(external_keycloak_uri) }}/auth/admin/realms/{{ che_keycloak_realm }}/identity-provider/instances"
    method: POST
    body: "{{ lookup('template', 'openshift-identity-provider.json.j2') }}"
    validate_certs: no
    body_format: json
    headers:
      Authorization: "bearer {{ keycloak_auth_response.json.access_token }}"
    status_code: 201

- name: "Create oAuth client at a cluster scope"
  openshift_v1_o_auth_client:
    state: present
    name: "{{ oauth_client_name }}"
    secret: "{{ identity_provider_client_secret }}"
    grant_method: prompt

- name: "Update oAuth client with redirectURIs"
  openshift_v1_o_auth_client:
    state: present
    name: "{{ oauth_client_name }}"
    secret: "{{ identity_provider_client_secret }}"
    redirect_ur_is:
    - "{{ keycloak_uri | default(external_keycloak_uri) }}/auth/realms/{{ che_keycloak_realm }}/broker/openshift-v3/endpoint"
    grant_method: prompt
