---

# Che Configuration
application_name: "codeready"
che_image_name: "eclipse/che-server"
che_image_tag: "latest"

che_infrastructure_active: "openshift"
che_debug_server: "false"
che_port: "8080"
che_local_conf_dir: "/etc/conf"
che_logs_dir: "/data/logs"
che_log_level: "INFO"
che_multiuser: "true"
che_predefined_stacks_reload__on__start: "true"
che_workspace_auto_start: "true"

che_server_deployment_strategy: "Rolling"
che_server_image_pull_policy: "IfNotPresent"
che_http_proxy_java_options: ""
che_server_java_opts: "-XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Xms20m {{ che_http_proxy_java_options }}"
che_workspace_java_options: "-XX:MaxRAM=150m -XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom {{ che_http_proxy_java_options }}"
che_workspace_maven_options: "-XX:MaxRAM=150m -XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom {{ che_http_proxy_java_options }}"
che_workspace_http_proxy: ""
che_workspace_https_proxy: ""
che_workspace_no_proxy: ""

# PostgreSQL Che Configuration
che_jdbc_db_host: "postgres"
che_jdbc_db_port: 5432
che_jdbc_db_name: "dbche"
che_jdbc_username: "pgche"
che_jdbc_password: "pgchepassword"
che_jdbc_url: "jdbc:postgresql://{{ che_jdbc_db_host }}:{{ che_jdbc_db_port }}/{{ che_jdbc_db_name }}"

# Keycloak Che Configuration
che_keycloak_client__id: "che-public"
che_keycloak_realm: "che"


# Kubernetes PVC
che_infra_kubernetes_pvc_precreate__subpaths: "false"
che_infra_kubernetes_pvc_quantity: "1Gi"
che_infra_kubernetes_pvc_strategy: "common"
che_infra_kubernetes_pvc_name: "claim-che-workspace"

# Kubernetes / OpenShift Config
che_infra_kubernetes_machine__start__timeout__min: "5"
che_infra_kubernetes_master__url: ""
che_infra_kubernetes_trust__certs: "false"
che_infra_openshift_tls__enabled: "false"

che_infra_openshift_project: "{{ namespace }}"
